apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.dotnet.name}}
  namespace: {{ .Values.globalparam.namespace}}
spec:
  replicas: {{ .Values.dotnet.replicas }}
  strategy:
    canary:
      canaryService: {{ .Values.dotnet.name}}-canary
      stableService: {{ .Values.dotnet.name}}-stable
      steps:
        - setWeight: 20
        - pause: { duration: 10s }
        - setWeight: 50
        - pause: { duration: 20s }
        - setWeight: 100
      analysis:
        templates:
        - templateName: {{ .Values.globalparam.templateName}}
        args:
        - name: {{ .Values.globalparam.argName}}
          value: {{ .Values.dotnet.argsValue}}
  selector:
    matchLabels:
      app: {{ .Values.dotnet.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.dotnet.name}}
    spec:
      serviceAccountName: {{ .Values.dotnet.serviceAccountName}}
      containers:
      - name: {{ .Values.dotnet.name}}
        image: {{ .Values.dotnet.image}}
        ports:
        - containerPort: {{ .Values.dotnet.number}}
        env:
        - name: MY_SECRET_VALUE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.vault.name}}
              key: {{ .Values.vault.secretKey}}
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      annotations:
        vault.security.banzaicloud.io/vault-addr: "http://vault.vault:8200"
        vault.security.banzaicloud.io/vault-role: "myapp-role"
        vault.security.banzaicloud.io/vault-path: "{{ .Values.vault.secretPath }}"
        vault.security.banzaicloud.io/vault-skip-verify: "true"
