apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dotnet.name}}-stable
  namespace: {{ .Values.globalparam.namespace}}
spec:
  selector:
    app: {{ .Values.dotnet.name}}
  ports:
    - protocol: TCP
      port: {{ .Values.dotnet.number}}
      targetPort: {{ .Values.dotnet.number}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dotnet.name}}-canary
  namespace: {{ .Values.globalparam.namespace}}
spec:
  selector:
    app: {{ .Values.dotnet.name}}
  ports:
    - protocol: TCP
      port: {{ .Values.dotnet.number}}
      targetPort: {{ .Values.dotnet.number}}