apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-stable
  namespace: lib
spec:
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-app-canary
  namespace: lib
spec:
  selector:
    app: dotnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80