apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.go.name}}
  namespace: {{ .Values.globalparam.namespace}}
spec:
  replicas: {{ .Values.go.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.go.name}}
  template:
    metadata:
      labels:
        app: {{ .Values.go.name}}
      annotations:
        vault.security.banzaicloud.io/vault-addr: {{ .Values.go.annotations.vaultAddr}}
        vault.security.banzaicloud.io/vault-role: {{ .Values.go.annotations.vaultRole}}
        vault.security.banzaicloud.io/vault-path: {{ .Values.go.annotations.vaultPath}}
        vault.security.banzaicloud.io/vault-skip-verify: {{ .Values.go.annotations.vaultVerify}}
    spec:
      containers:
      - name: {{ .Values.go.name}}
        image: {{ .Values.go.image }}
        ports:
        - containerPort: {{ .Values.go.number}}
        env:
        - name: MY_SECRET_VALUE
          valueFrom:
            secretKeyRef:
              name: {{ .Values.vault.name}}
              key: {{ .Values.vault.secretKey }}
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
