apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.go.name}}
  namespace: {{ .Values.globalparam.namespace}}
spec:
  selector:
    app: {{ .Values.go.name}}
  ports:
    - protocol: TCP
      port: {{ .Values.go.number}}
      targetPort: {{ .Values.go.number}}