{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name}}
  namespace: {{ .Values.globalparam.namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.dotnet.name}}
                port:
                  number: {{ .Values.dotnet.number}}
          - path: /go
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.go.name}}
                port:
                  number: {{ .Values.go.number}}
{{- end }}
