apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: error-rate
  namespace: lib
spec:
  args:
    - name: failure-threshold
  metrics:
    - name: error-rate
      interval: 30s
      count: 3
      successCondition: "result < 95"
      provider:
        prometheus:
          address: http://prometheus.monitoring:9090
          query: |
            sum(rate(nginx_ingress_controller_requests{status=~"5.."}[1m])) 
            /
            sum(rate(nginx_ingress_controller_requests[1m])) * 100