apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Values.analysis.name}}
  namespace: {{ .Values.globalparam.namespace}}
spec:
  args:
    - name: {{ .Values.analysis.argName}}
  metrics:
    - name: {{ .Values.analysis.name}}
      interval: 30s
      count: 3
      successCondition: {{ .Values.analysis.successCondition}}
      provider:
        prometheus:
          address: {{ .Values.analysis.prometheus.address}}
          query: |
            sum(rate(nginx_ingress_controller_requests{status=~"5.."}[1m])) 
            /
            sum(rate(nginx_ingress_controller_requests[1m])) * 100