apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress
  labels:
    release: prometheus  # должен совпадать с release Prometheus Operator в твоём helm release
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  namespaceSelector:
    matchNames:
      - ingress-nginx  # или другой namespace, где запущен ingress-контроллер
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
