apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.monitor.name}}
  namespace: {{ .Values.globalparam.namespace}}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.monitor.matchLabels.appName}}
      app.kubernetes.io/component: {{ .Values.monitor.matchLabels.appComponent}}
  namespaceSelector:
    matchNames:
      - {{ .Values.monitor.matchNames.name}}
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
