dotnet:
  image: dotnetcorelibrary:latest
  replicas: 2

go:
  image: go-search-service:latest
  replicas: 1

vault:
  secretPath: secret/data/myapp
  secretKey: MY_SECRET_KEY

ingress:
  enabled: true
  host: myapp.local
